chain:
    bech32_prefix: impy
    modules: []
node:
    type: remote
    config:
        rpc:
            client_name: juno
            address: http://75.119.137.73:26657
            max_connections: 20
        grpc:
            address: localhost:9090
            insecure: true
parsing:
    workers: 1
    start_height: 1
    average_block_time: 5s
    listen_new_blocks: true
    parse_old_blocks: true
    parse_genesis: true
database:
    url: postgres://user_user:123_pass@localhost:5432/bdjuno?sslmode=disable&search_path=public
    max_open_connections: 1
    max_idle_connections: 1
    partition_size: 100000
    partition_batch: 1000
    ssl_mode_enable: "false"
logging:
    level: debug
    format: text
actions:
    host: 127.0.0.1
    port: 3000
